version: '3'
services:
  web:
    image: maven
    ports:
      - "8080:8080"
    volumes:
      - ./backend/app/weather:/app/weather
    working_dir: /app/weather
    container_name: backend
    links:
      - mongodb
    depends_on:
      - mongodb
    command: mvn spring-boot:run
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/app/weatherFrontApp:/app
    ports:
      - 4200:4200
    working_dir: /app
    command: npm run start-docker
